### ISSUE TITLE
can not download jar

### ISSUE THREAD

**Issue by yuquanle** [SAG-KeLP/kelp-input-generator#3]
hi everyone:
              This depends on the package that I downloaded for a week and failed. Is there any other way?

              <dependency>
			<groupId>edu.stanford.nlp</groupId>
			<artifactId>stanford-corenlp</artifactId>
			<version>3.7.0</version>
			<classifier>models</classifier>
		</dependency>
                                                                    
Best regards,
yuquanle

**Comment by kamei86i** [comment]
It is very strange. This dependency should be available in Maven Central. Can you normally reach the Maven central repository?

**Comment by yuquanle** [comment]
thanks for your reply. I have solve it. It is the network problem.
